### ISSUE TITLE
Permanently File Deletion

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#1]
**From the user's perspective:**

- [x] The user can delete files he owns permanently by selecting and pressing the delete key/button.

- [x]  In case of folders, the folder and it's content will be permanently deleted.

- [x] The user should be able to select and delete multiple files simultaneously.

- [x] The user will be notified that his action is going to delete all of the folder's content, and the user would have to confirm it. (should we do it)?

**Behind the scenes:**

- [x] For each file, the UI send a request to the API.

- [x] The API calls file-service with the given file-id.

- [x] The file-service deletes the file and all of its decedents (in case of a folder). The service returns an array of {id, key, bucket} of all the deleted files. : Shahar, 7.8

- [x] The API gets the array of {id, key, bucket} and delete those files from (upload-service).

- [x] The upload-service gets a list of  keys, and a bucket (that they are in), delete the objects from the s3, and returns an array of deleted keys and of the failed keys.

- [x] The API returns the array of deleted file-ids (from the file-service), after the request to the upload-service.

**Questions:**

- From where do we delete first? - DB.

- How do we handle deletion failure? 
     In case the DB deletion failed, the file id won't be returned in the file-service.
     In case of failure in the Object Storage, there won't be indication for that for now.

- How do we handle it in case of multiple files or in case we delete a folder?

- Remember to modify the feature when planning the share. for example, we need to verify permission before deleting each file.

- We need to separate the files sent to upload-service by bucket  ( a new request for each bucket) (share).
