### ISSUE TITLE
Adjust File Browser to our API

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#13]
- [x]  ~Add server side rendering (for configuration)~ Add configuration fetching from api-gateway (/api/config)
- [ ]  Add apm
- [ ] Add configuration field in api-gateway for authentication url to use in [auth util in the ui](https://github.com/meateam/web-ui/blob/0bea7e97bd882cc8313333d3fca7d35074800367/src/utils/auth.js#L69)
- [x] Fix login page not redirecting to authentication when clearing `kd-token` cookie but `jwt` is still set in the localStorage

**Comment by omrishtam** [comment]
Implemented configuration fetching from api-gateway like it was before, without server side rendering.
APM works only for `fetchURL` function in utils.

**Comment by omrishtam** [comment]
@omerzamir Should add configuration for auth url for the ui so that we won't have to change it each time we work on the ui locally with a different hardcoded url.
