### ISSUE TITLE
Update File's Metadata

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#16]
**From the user's perspective:**
- [x] The user able to select a file he owns and change it's name.
- [x] The user able to select multiple files he owns and move them to a new folder.

**Behind the scenes:**
- [x] The user needs to have an interface to change a file's name.
- [x] After file selection the user can drag the selected files to a folder in the folder view.
- [x] After file selection the user can open an interface where he can select a folder to move the selected files to.
- [x] The API needs to check permissions before updating the file's metadata:
  - [x] The user needs to own the file.
  - [x] In case of location (`parentId`) change, the user need to also own the folder (the new `parentId`).
- [x] The API send a request to the file-service to update the file metadata.
- [x] The file-service gets an array of file ids and partial file and update them in the DB by the partial file. The return value is an array of the succeeded file ids.
- [x] The API gets the results and returns the new updated file-ids.

**Questions:**
- Should UI send a single or multiple request to the API when multiple files are moved?
- Is sending the IDs that succeeded is enough?
- Should we return the new file and not just it's id?
- How do we handle the files that failed to be updated?
- For optimization purposes, we can use the `updateMany` query when updating the documents (in case of folder change)? - It seems like Mongo doesn't return the succeeded or failed  ids/object in `UpdateMany`.

**Comment by omerzamir** [comment]
File service isn't getting a list of ids, as of now a partial file is expected. 
we should change the file service implementation first, then proceed with api-gateway.
