### ISSUE TITLE
Customer support link

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#19]
- [x] The user should have a link to a support channel.
**Tasks:**
- [x] The API need to have a configurable (env var) link to the support channel.
- [x] The API should export this link in the /api/config route.
- [x] The web-ui should save the support link in the state and display it in the sidebar
