### ISSUE TITLE
User's Quota

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#20]
- [x] The user sees his quota i.e. the maximum size limit of the storage allocated for him, and how much storage he has used.
- [x] Operations like Upload and Delete update the quota displayed to the user.
- [ ] If the user have no more space left when uploading, the upload should be canceled and the user need to be notified of the reason.

**Tasks**
- [x] There should be a bar in the main page showing the used space of the user relatively to his quota.
- [x] The user's quota should be accessible to the UI through an API route: `/api/users/userId/quota`.
- [x] When uploading and deleting files, the files service should update the user's quota.
- [x] After uploading or deleting files, the UI need to hold the correct quota, by requesting the user's quota after those kind of actions.
- [x] The File-service will provide a function in a new service which will check if a user can get someone else's quota - _for now, a user can only get his quota_.
- [x] Before the API fetch a user quota it should check permissions with the above function.

**Comments**
- In later versions we should alert the user when he is approaching his size limit.
