### ISSUE TITLE
File Sharing v1

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#3]
Detailed extensively in the [drive](https://docs.google.com/document/d/177icM91Vkmberg09qbj0pKZJWV_dfPgbcSUClLITx6U/edit#).
Will be updated later on the [wiki](https://github.com/meateam/project/wiki/File-Share---v1).

- [x] The user is able to give a read permission for other users to files he owns.
If it is a folder, the permission will seep into the folder descendants.
- [x] The owner is able to do the sharing process via the share dialog, where he can search and find other users.
- [x] The user can see all the other users shared a the file he has access to.
- [x] The shared user can watch the files directly shared with him in his "Shared With Me" folder.
- [x] The owner is able to unshare i.e. revoke the permission given to a user on a file he directly shared. After the unshare action, the previously shared user will now have no access to those files, and their descendant, unless one of the ancestors is already shared or that some of those sub-files were directly shared before the share of their ancestor.  
- [x] The owner can view the users shared with the file and unshare them in the share dialog.

### Create Permission
- [x] When files are selected in `My Files` view, the user can press the share button which will open the share dialog.

### Searching and population users
- [x] In the `Share Dialog` the owner can see all the users (name and id) that are shared with the file.
- [x] Also in the `Share Dialog` the owner can search and find users by name and id to share the file with. 

### Permission-service
- [x] create permission with `userID` , `fileID` and `role`.
- [x] delete a permission by `userID` and `fileID`.
- [x] get a permissions by  `fileID`.
- [x] check if a user have a certain role (or higher) on a certain file.
### API Gateway
- [x] create a permission
- [x] delete a permission
- [x] Create a permission-middleware that is called any time a user is requesting a operation on a file, and checks that the user has a sufficient permission for that.
#### Changes to current API:
- [ ] Create a permission for the owner in the file-upload operation.
- [ ] Delete all of a file's permission in a file-delete operation.
- [ ] Add options to ask for a specific file fields in the get-file/s operations.
### User Service:
- [x] Get user suggestions by partial user full name.
- [x] Get user by id.
- [x] Connect to Kartoffel using Spike's token.
