### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#6]
**From the user's perspective:**

- [x] The user is able to create a folder inside his root or inside one of his folders.

- [x]  The user is able to move files he own to a folder he owns.

- [x] The user is able to enter the folder and see all the files in the folder.

- [x] The user is able to upload files directly to a folder he owns.

- [x] The user is able to go one folder up (unless it is his root folder).

**Behind the scenes:**

- [x] The file service will create a new file with type folder in the DB.

- [x] From now on, a created file parent will be the folder id in which the user were in when he uploaded the file.

- When moving a file to different folder, the file's `parentId` filed will change to the new folder id:
    - [x] UI
    - [x] API
    - [x] File Service

- [x] We should also check that the `ownerID` of the new folder is the id of the requesting user.

- [x] We need to implement `getFilesByFolder`.

- [x] The client needs to save the current folder the user is in.

**Questions:**

- How and when we calculate a folder size?
